# Languages

# Default language
de:
  languageCode: de
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/de

en:
  languageCode: en-us
  contentDir: content/en
  title: PedScience Research Institute
  menu:
    main:
      - name: News
        url: "post"
        weight: 1
      - name: Team
        url: "people"
        weight: 2
      - name: Projects
        url: "project"
        weight: 3
      - name: Publications
        url: "publication"
        weight: 4
      - name: Contact
        url: "contact"
        weight: 5

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
